//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalorieLevel
    {
        public int CalorieLevelID { get; set; }
        public double CalorieAmount { get; set; }
        public double CalorieLevelLimit { get; set; }
        public double ComparedCalorieLevel { get; set; }
        public int MealId { get; set; }
    
        public virtual Meal Meal { get; set; }
    }
}
