//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DMDBEntities : DbContext
    {
        public DMDBEntities()
            : base("name=DiabetesManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalorieLevel> CalorieLevels { get; set; }
        public virtual DbSet<Meal> Meals { get; set; }
        public virtual DbSet<MealGlucoseLevel> MealGlucoseLevels { get; set; }
        public virtual DbSet<MonthlyInput> MonthlyInputs { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<SuggestMeal> SuggestMeals { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
