//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealGlucoseLevel
    {
        public int GlucoseLevelID { get; set; }
        public double GlucoseLevel { get; set; }
        public double GlucoseLevelLimit { get; set; }
        public double ComparedGlucoseLevel { get; set; }
        public int MealId { get; set; }
    
        public virtual Meal Meal { get; set; }
    }
}
